/// Placeholder generated by the Swift Package Manager template.
///
/// Kept only for source compatibility; it has no functionality.
@available(*, deprecated, message: "ToastLauncher has no functionality. Use the toastView(isPresented:...) modifier instead.")
public struct ToastLauncher {
    public private(set) var text = "Hello, World!"

    public init() {
    }
}
